spring.application.name=MyFocusTime

# Datos de conexión PostgreSQL directamente
spring.datasource.url=jdbc:postgresql://dpg-d4qpfc8gjchc73bgj910-a.oregon-postgres.render.com:5432/myfocustime
spring.datasource.username=myfocustime_user
spring.datasource.password=njHKIOB2MxpL4U94CwcpvIenX6fSJkgS
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
